# Generated by Django 5.1.3 on 2024-11-25 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_vaccine_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_consumed', models.FloatField()),
                ('water_consumed', models.FloatField()),
                ('date_fed', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='animals.animal')),
            ],
        ),
    ]
