# Generated by Django 5.1.3 on 2024-11-25 21:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_is_pregnant_feedingrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineapplication',
            name='vaccine',
        ),
        migrations.RemoveField(
            model_name='vaccineapplication',
            name='animal',
        ),
        migrations.CreateModel(
            name='DailyFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('food_amount', models.FloatField()),
                ('water_amount', models.FloatField()),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_feeds', to='animals.animal')),
            ],
        ),
        migrations.DeleteModel(
            name='FeedingRecord',
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
        migrations.DeleteModel(
            name='VaccineApplication',
        ),
    ]
