# Generated by Django 5.1.3 on 2024-11-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_remove_vaccineapplication_vaccine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dailyfeed',
            name='animal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animals.animal'),
        ),
        migrations.AlterField(
            model_name='dailyfeed',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dailyfeed',
            name='food_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyfeed',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyfeed',
            name='water_amount',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='VaccineApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_applications', to='animals.animal')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='animals.vaccine')),
            ],
        ),
    ]
