# Generated by Django 5.1.3 on 2024-11-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
